<?php

namespace Container1quM9PQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginControllerService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShopBundle\Controller\Admin\LoginController' shared autowired service.
     *
     * @return \PrestaShopBundle\Controller\Admin\LoginController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['PrestaShopBundle\\Controller\\Admin\\LoginController'] = $instance = new \PrestaShopBundle\Controller\Admin\LoginController(($container->privates['PrestaShop\\PrestaShop\\Core\\Context\\ShopContext'] ?? self::getShopContext2Service($container)), \dirname(__DIR__, 5), 'admin920qwe5isyiw2fkwogd');

        $instance->setContainer(($container->privates['.service_locator.4bDe9Ei'] ?? $container->load('get_ServiceLocator_4bDe9EiService'))->withContext('PrestaShopBundle\\Controller\\Admin\\LoginController', $container));

        return $instance;
    }
}
