<?php

namespace Container1quM9PQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTagControllerService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShopBundle\Controller\Admin\Configure\ShopParameters\TagController' shared autowired service.
     *
     * @return \PrestaShopBundle\Controller\Admin\Configure\ShopParameters\TagController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['PrestaShopBundle\\Controller\\Admin\\Configure\\ShopParameters\\TagController'] = $instance = new \PrestaShopBundle\Controller\Admin\Configure\ShopParameters\TagController();

        $instance->setContainer(($container->privates['.service_locator.4bDe9Ei'] ?? $container->load('get_ServiceLocator_4bDe9EiService'))->withContext('PrestaShopBundle\\Controller\\Admin\\Configure\\ShopParameters\\TagController', $container));

        return $instance;
    }
}
