<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1quM9PQ\AdminKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1quM9PQ/AdminKernelProdContainer.php') {
    touch(__DIR__.'/Container1quM9PQ.legacy');

    return;
}

if (!\class_exists(AdminKernelProdContainer::class, false)) {
    \class_alias(\Container1quM9PQ\AdminKernelProdContainer::class, AdminKernelProdContainer::class, false);
}

return new \Container1quM9PQ\AdminKernelProdContainer([
    'container.build_hash' => '1quM9PQ',
    'container.build_id' => '0e74e59a',
    'container.build_time' => 1786541702,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container1quM9PQ');
